set_property PACKAGE_PIN V8 [get_ports RST_0]
set_property IOSTANDARD LVCMOS33 [get_ports RST_0]
set_property IOSTANDARD LVCMOS33 [get_ports CS_0]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports SDI_0]
set_property IOSTANDARD LVCMOS33 [get_ports SDO_0]
set_property PACKAGE_PIN V10 [get_ports SDI_0]
set_property PACKAGE_PIN W10 [get_ports CS_0]
set_property PACKAGE_PIN Y16 [get_ports SCLK_0]
set_property PACKAGE_PIN Y17 [get_ports SDO_0]

set_property PACKAGE_PIN W9 [get_ports zero]
set_property IOSTANDARD LVCMOS33 [get_ports zero]

set_property PACKAGE_PIN U8 [get_ports wifi_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports wifi_rxd]
set_property PACKAGE_PIN U7 [get_ports wifi_txd]
set_property IOSTANDARD LVCMOS33 [get_ports wifi_txd]

set_property PACKAGE_PIN M20 [get_ports {SW_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_tri_i[0]}]
set_property PACKAGE_PIN M19 [get_ports {SW_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_tri_i[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {btns_4bits_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_4bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_4bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CTL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CTL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CTL[2]}]

set_property PACKAGE_PIN D19 [get_ports {btns_4bits_tri_i[0]}]
set_property PACKAGE_PIN D20 [get_ports {btns_4bits_tri_i[1]}]
set_property PACKAGE_PIN L20 [get_ports {btns_4bits_tri_i[2]}]
set_property PACKAGE_PIN L19 [get_ports {btns_4bits_tri_i[3]}]
set_property PACKAGE_PIN V6 [get_ports {CTL[0]}]
set_property PACKAGE_PIN W19 [get_ports {CTL[1]}]
set_property PACKAGE_PIN W18 [get_ports {CTL[2]}]